# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/yuandao/n70/setup-makefiles.sh


PRODUCT_COPY_FILES += \
  vendor/yuandao/n70/proprietary/app/RkExplorer.apk:system/app/RkExplorer.apk \
  vendor/yuandao/n70/proprietary/lib/libEGL.so:system/lib/libEGL.so \
  vendor/yuandao/n70/proprietary/lib/libMali.so:system/lib/libMali.so \
  vendor/yuandao/n70/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
  vendor/yuandao/n70/proprietary/lib/libUMP.so:system/lib/libUMP.so \
  vendor/yuandao/n70/proprietary/lib/libapedec.so:system/lib/libapedec.so \
  vendor/yuandao/n70/proprietary/lib/libgui.so:system/lib/libgui.so \
  vendor/yuandao/n70/proprietary/lib/libion.so:system/lib/libion.so \
  vendor/yuandao/n70/proprietary/lib/libjpeghwdec.so:system/lib/libjpeghwdec.so \
  vendor/yuandao/n70/proprietary/lib/libjpeghwenc.so:system/lib/libjpeghwenc.so \
  vendor/yuandao/n70/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
  vendor/yuandao/n70/proprietary/lib/libomxvpu.so:system/lib/libomxvpu.so \
  vendor/yuandao/n70/proprietary/lib/libril-rk29-dataonly.so:system/lib/libril-rk29-dataonly.so \
  vendor/yuandao/n70/proprietary/lib/librkswscale.so:system/lib/librkswscale.so \
  vendor/yuandao/n70/proprietary/lib/librkwmapro.so:system/lib/librkwmapro.so \
  vendor/yuandao/n70/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
  vendor/yuandao/n70/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
  vendor/yuandao/n70/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/yuandao/n70/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
  vendor/yuandao/n70/proprietary/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
  vendor/yuandao/n70/proprietary/lib/libvpu.so:system/lib/libvpu.so \
  vendor/yuandao/n70/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
  vendor/yuandao/n70/proprietary/lib/libyuvtorgb.so:system/lib/libyuvtorgb.so \
  vendor/yuandao/n70/proprietary/lib/registry:system/lib/registry \
  vendor/yuandao/n70/proprietary/lib/stagefright.ver:system/lib/stagefright.ver \
  vendor/yuandao/n70/proprietary/lib/webkit_ver:system/lib/webkit_ver \
  vendor/yuandao/n70/proprietary/etc/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \
  vendor/yuandao/n70/proprietary/etc/firmware/bdata.SD31.bin:system/etc/firmware/bdata.SD31.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/device.bin:system/etc/firmware/device.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_RK901.bin:system/etc/firmware/fw_RK901.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_RK903.bin:system/etc/firmware/fw_RK903.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_RK903_p2p.bin:system/etc/firmware/fw_RK903_p2p.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4319.bin:system/etc/firmware/fw_bcm4319.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4329_wapi.bin:system/etc/firmware/fw_bcm4329_wapi.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4330.bin:system/etc/firmware/fw_bcm4330.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/fw_bcm4330_apsta.bin:system/etc/firmware/fw_bcm4330_apsta.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_4330.txt:system/etc/firmware/nvram_4330.txt \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_RK901.txt:system/etc/firmware/nvram_RK901.txt \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_RK903.cal:system/etc/firmware/nvram_RK903.cal \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_RK903.txt:system/etc/firmware/nvram_RK903.txt \
  vendor/yuandao/n70/proprietary/etc/firmware/nvram_RK903_26M.cal:system/etc/firmware/nvram_RK903_26M.cal \
  vendor/yuandao/n70/proprietary/etc/firmware/otp.bin.z77:system/etc/firmware/otp.bin.z77 \
  vendor/yuandao/n70/proprietary/etc/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \
  vendor/yuandao/n70/proprietary/etc/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \
  vendor/yuandao/n70/proprietary/lib/hw/audio.primary.rk30board.so:system/lib/hw/audio.primary.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/audio_policy.rk30board.so:system/lib/hw/audio_policy.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/camera.rk30board.so:system/lib/hw/camera.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/copybit.rk30board.so:system/lib/hw/copybit.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/gpu.rk30board.so:system/lib/hw/gpu.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/gralloc.rk30board.so:system/lib/hw/gralloc.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/hwcomposer.rk30board.so:system/lib/hw/hwcomposer.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/lights.rk30board.so:system/lib/hw/lights.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/hw/sensors.rk30board.so:system/lib/hw/sensors.rk30board.so \
  vendor/yuandao/n70/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
  vendor/yuandao/n70/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
  vendor/yuandao/n70/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
  vendor/yuandao/n70/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
  vendor/yuandao/n70/proprietary/bin/akmd8975:system/bin/akmd8975 \
  vendor/yuandao/n70/proprietary/bin/fsck.exfat:system/bin/fsck.exfat \
  vendor/yuandao/n70/proprietary/bin/hostapd_rtl:system/bin/hostapd_rtl \
  vendor/yuandao/n70/proprietary/bin/mkfs.exfat:system/bin/mkfs.exfat \
  vendor/yuandao/n70/proprietary/bin/mkntfs:system/bin/mkntfs \
  vendor/yuandao/n70/proprietary/bin/mount.exfat:system/bin/mount.exfat \
  vendor/yuandao/n70/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
  vendor/yuandao/n70/proprietary/bin/ntfs-3g.probe:system/bin/ntfs-3g.probe \
  vendor/yuandao/n70/proprietary/bin/performance:system/bin/performance \
  vendor/yuandao/n70/proprietary/bin/surfaceflinger:system/bin/surfaceflinger \
  vendor/yuandao/n70/proprietary/bin/wpa_cli:system/bin/wpa_cli \
  vendor/yuandao/n70/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant
